name: "Analyzer"

on:
  schedule:
    - cron: '17 18 * * 1'

jobs:
  IWYU:
    name: Check includes
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: Pikafish/src
        shell: bash
    steps:
      - name: Checkout Pikafish
        uses: actions/checkout@v6
        with:
          path: Pikafish

      - name: Checkout include-what-you-use
        uses: actions/checkout@v6
        with:
          repository: include-what-you-use/include-what-you-use
          ref: 0.26
          path: include-what-you-use
          persist-credentials: false

      - name: Download required linux packages
        run: |
          sudo add-apt-repository 'deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-17 main'
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo apt update
          sudo apt install -y libclang-17-dev clang-17 libc++-17-dev

      - name: Set up include-what-you-use
        run: |
          mkdir build && cd build
          cmake -G "Unix Makefiles" -DCMAKE_PREFIX_PATH="/usr/lib/llvm-17" ..
          sudo make install
        working-directory: include-what-you-use

      - name: Check include-what-you-use
        run: include-what-you-use --version

      - name: Check includes
        run: >
          make analyze
          COMP=clang
          CXX=include-what-you-use
          CXXFLAGS="-stdlib=libc++ -Xiwyu --comment_style=long -Xiwyu --mapping='${{ github.workspace }}/Pikafish/.github/workflows/libcxx17.imp' -Xiwyu --error"

  Clang-Format:
    name: Check format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Pikafish
        uses: actions/checkout@v6

      - name: Run clang-format style check
        uses: jidicula/clang-format-action@v4.18.0
        id: clang-format
        with:
          clang-format-version: '22'