name: Tune

on:
  push:
    branches:
      - tune

jobs:
  linux:
    env:
      COMP: clang
      ARCH: x86-64-universal
    defaults:
      run:
        working-directory: src
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v6

      - name: Set up LLVM
        if: runner.os == 'Linux'
        run: |
          LLVM_VERSION=22
          curl -s https://apt.llvm.org/llvm.sh | sudo bash -s -- $LLVM_VERSION
          sudo apt install -y libc++-$LLVM_VERSION-dev libc++abi-$LLVM_VERSION-dev libunwind-$LLVM_VERSION-dev
          echo "EXTRACXXFLAGS=-stdlib=libc++" >> $GITHUB_ENV
          echo "EXTRALDFLAGS=-stdlib=libc++" >> $GITHUB_ENV
          echo "/usr/lib/llvm-$LLVM_VERSION/bin" >> $GITHUB_PATH

      - name: make
        run: make -j build && make strip

      - name: upload to fishtest
        run: curl https://test.pikafish.org/api/pre_upload -F file=@pikafish -F "file_type=engine" -F "password=${{ secrets.NOTHING }}"

      - name: print variables table
        run: printf 'quit' | ./pikafish